=head1 NAME

HTML::WikiConverter::FreeStyleWiki -

=head1 SYNOPSIS

  use HTML::WikiConverter::FreeStyleWiki;

=head1 DESCRIPTION

HTML::WikiConverter::FreeStyleWiki is

=head1 AUTHOR

Yusuke Watase E<lt>ywatase@gmail.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

